export const EDIT_PAGE_MOUNTED = 'EDIT_PAGE_MOUNTED';
export const VERSION_IS_SUBMITTING = 'VERSION_IS_SUBMITTING';
export const SUBMITTING_HAS_ERRORED = 'SUBMITTING_HAS_ERRORED';
export const SUBMITTING_POST_SUCCESS = 'SUBMITTING_POST_SUCCESS';